# Generated by Django 4.2.8 on 2026-02-09 07:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_historicalcustomuser'),
    ]

    operations = [
        migrations.DeleteModel(
            name='HistoricalCustomUser',
        ),
    ]
