# Generated by Django 4.2.8 on 2026-02-09 22:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0003_historicalshift_historicalpatient_historicalnote_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalpatient',
            name='age',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='historicalpatient',
            name='created_by',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='patient',
            name='age',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='patient',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_patients', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='historicalpatient',
            name='admission_date',
            field=models.DateField(blank=True, editable=False),
        ),
        migrations.AlterField(
            model_name='historicalpatient',
            name='severity',
            field=models.CharField(default='Unknown', max_length=50),
        ),
        migrations.AlterField(
            model_name='patient',
            name='admission_date',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='severity',
            field=models.CharField(default='Unknown', max_length=50),
        ),
    ]
