# Generated by Django 4.2.8 on 2026-02-09 22:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import simple_history.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0004_historicalpatient_age_historicalpatient_created_by_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalObservation',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('timestamp', models.DateTimeField(blank=True, editable=False)),
                ('blood_pressure_systolic', models.IntegerField(blank=True, help_text='Systolic BP (mmHg)', null=True)),
                ('blood_pressure_diastolic', models.IntegerField(blank=True, help_text='Diastolic BP (mmHg)', null=True)),
                ('temperature', models.DecimalField(blank=True, decimal_places=1, help_text='Temperature (°C)', max_digits=4, null=True)),
                ('pulse', models.IntegerField(blank=True, help_text='Heart rate (bpm)', null=True)),
                ('respiratory_rate', models.IntegerField(blank=True, help_text='Breaths per minute', null=True)),
                ('oxygen_saturation', models.IntegerField(blank=True, help_text='SpO2 (%)', null=True)),
                ('notes', models.TextField(blank=True, help_text='Nurse observations and patient status')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('nurse', models.ForeignKey(blank=True, db_constraint=False, limit_choices_to={'role': 'nurse'}, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('patient', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='core.patient')),
            ],
            options={
                'verbose_name': 'historical observation',
                'verbose_name_plural': 'historical observations',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='Observation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('blood_pressure_systolic', models.IntegerField(blank=True, help_text='Systolic BP (mmHg)', null=True)),
                ('blood_pressure_diastolic', models.IntegerField(blank=True, help_text='Diastolic BP (mmHg)', null=True)),
                ('temperature', models.DecimalField(blank=True, decimal_places=1, help_text='Temperature (°C)', max_digits=4, null=True)),
                ('pulse', models.IntegerField(blank=True, help_text='Heart rate (bpm)', null=True)),
                ('respiratory_rate', models.IntegerField(blank=True, help_text='Breaths per minute', null=True)),
                ('oxygen_saturation', models.IntegerField(blank=True, help_text='SpO2 (%)', null=True)),
                ('notes', models.TextField(blank=True, help_text='Nurse observations and patient status')),
                ('nurse', models.ForeignKey(limit_choices_to={'role': 'nurse'}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='observations', to='core.patient')),
            ],
            options={
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['patient', '-timestamp'], name='core_observ_patient_125eee_idx'), models.Index(fields=['nurse', '-timestamp'], name='core_observ_nurse_i_547bfe_idx')],
            },
        ),
    ]
