# Generated by Django 4.2.8 on 2026-02-11 11:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import simple_history.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0005_historicalobservation_observation'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalTestOrder',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('test_type', models.CharField(help_text='Type of test (e.g., CBC, X-Ray, MRI)', max_length=200)),
                ('status', models.CharField(choices=[('ordered', 'Ordered'), ('pending', 'Pending'), ('resulted', 'Resulted'), ('cancelled', 'Cancelled')], default='ordered', max_length=20)),
                ('notes', models.TextField(blank=True, help_text='Additional instructions or notes')),
                ('ordered_at', models.DateTimeField(blank=True, editable=False)),
                ('updated_at', models.DateTimeField(blank=True, editable=False)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('doctor', models.ForeignKey(blank=True, db_constraint=False, limit_choices_to={'role': 'doctor'}, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('patient', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='core.patient')),
            ],
            options={
                'verbose_name': 'historical test order',
                'verbose_name_plural': 'historical test orders',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalPrescription',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('medication', models.CharField(help_text='Medication name', max_length=200)),
                ('dosage', models.CharField(help_text='Dosage (e.g., 500mg, 10ml)', max_length=100)),
                ('frequency', models.CharField(help_text='Frequency (e.g., twice daily, every 6 hours)', max_length=100)),
                ('duration', models.CharField(blank=True, help_text='Duration (e.g., 7 days, 2 weeks)', max_length=100)),
                ('instructions', models.TextField(blank=True, help_text='Special instructions for patient')),
                ('prescribed_at', models.DateTimeField(blank=True, editable=False)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('doctor', models.ForeignKey(blank=True, db_constraint=False, limit_choices_to={'role': 'doctor'}, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('patient', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='core.patient')),
            ],
            options={
                'verbose_name': 'historical prescription',
                'verbose_name_plural': 'historical prescriptions',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalDiagnosis',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('diagnosis_text', models.TextField(help_text='Medical diagnosis and clinical findings')),
                ('timestamp', models.DateTimeField(blank=True, editable=False)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('doctor', models.ForeignKey(blank=True, db_constraint=False, limit_choices_to={'role': 'doctor'}, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('patient', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='core.patient')),
            ],
            options={
                'verbose_name': 'historical diagnosis',
                'verbose_name_plural': 'historical Diagnoses',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='TestOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test_type', models.CharField(help_text='Type of test (e.g., CBC, X-Ray, MRI)', max_length=200)),
                ('status', models.CharField(choices=[('ordered', 'Ordered'), ('pending', 'Pending'), ('resulted', 'Resulted'), ('cancelled', 'Cancelled')], default='ordered', max_length=20)),
                ('notes', models.TextField(blank=True, help_text='Additional instructions or notes')),
                ('ordered_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('doctor', models.ForeignKey(limit_choices_to={'role': 'doctor'}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='test_orders', to='core.patient')),
            ],
            options={
                'ordering': ['-ordered_at'],
                'indexes': [models.Index(fields=['patient', '-ordered_at'], name='core_testor_patient_48b8a0_idx'), models.Index(fields=['doctor', '-ordered_at'], name='core_testor_doctor__7ab248_idx'), models.Index(fields=['status'], name='core_testor_status_6a5421_idx')],
            },
        ),
        migrations.CreateModel(
            name='Prescription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medication', models.CharField(help_text='Medication name', max_length=200)),
                ('dosage', models.CharField(help_text='Dosage (e.g., 500mg, 10ml)', max_length=100)),
                ('frequency', models.CharField(help_text='Frequency (e.g., twice daily, every 6 hours)', max_length=100)),
                ('duration', models.CharField(blank=True, help_text='Duration (e.g., 7 days, 2 weeks)', max_length=100)),
                ('instructions', models.TextField(blank=True, help_text='Special instructions for patient')),
                ('prescribed_at', models.DateTimeField(auto_now_add=True)),
                ('doctor', models.ForeignKey(limit_choices_to={'role': 'doctor'}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prescriptions', to='core.patient')),
            ],
            options={
                'ordering': ['-prescribed_at'],
                'indexes': [models.Index(fields=['patient', '-prescribed_at'], name='core_prescr_patient_7f4146_idx'), models.Index(fields=['doctor', '-prescribed_at'], name='core_prescr_doctor__db5e64_idx')],
            },
        ),
        migrations.CreateModel(
            name='Diagnosis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('diagnosis_text', models.TextField(help_text='Medical diagnosis and clinical findings')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('doctor', models.ForeignKey(limit_choices_to={'role': 'doctor'}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='diagnoses', to='core.patient')),
            ],
            options={
                'verbose_name_plural': 'Diagnoses',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['patient', '-timestamp'], name='core_diagno_patient_6ef305_idx'), models.Index(fields=['doctor', '-timestamp'], name='core_diagno_doctor__576388_idx')],
            },
        ),
    ]
